-
  cache:
    - app/node_modules                        
    - '%APPDATA%\npm-cache'              
    - '%USERPROFILE%\.nuget\packages'
    - C:\Users\appveyor\.sonar

  version: 1.0.{build}

  image: Previous Visual Studio 2019

  environment:
    # These are sensitive values
    COVERALLS_REPO_TOKEN:
      secure: QxBrjZqijzG55XrPdRqGxPakw59SE8pOHazTGqL1PmMJaBIcUdNNo9LLK9x2HpQ9
    SONARQUBE_REPO_TOKEN:
      secure: utN0nHE2a123QVNOyKsU1r61KB5++x5XpjzEFB+5q2iB+7gOQxWHLZtfKtYsj2h8
    AZURE_PW:
      secure: yAoqN/1JcbJv27+yx7FFJrVGPS7ZLmv1S2/qLwi02b9js9KjqoH28M+Gk7lDAHGfsI9tNZLHL8+XHaPYGZ/ydg==
    APPVEYOR_TOKEN:
      secure: bxNIk9vGzx4u8owB2t2Vf8UNOBPZ3R2FJSliuOZ+L0I=
    # Might want to change these in UI.
    RESTORE_API: YES
    RESTORE_APP: YES
    BUILD_API: YES
    BUILD_APP: YES
    UNIT_TEST_API: YES
    UNIT_TEST_APP: YES
    INTEGRATION_TEST_API: YES
    INTEGRATION_TEST_APP: Unused
    BUILD_ARTIFACT: YES
    COVERAGE_REPORT_API: NO
    COVERAGE_REPORT_APP: NO
    UPLOAD_COVERALLS_API: YES
    UPLOAD_COVERALLS_APP: YES
    UPLOAD_SONARQUBE_API: YES
    UPLOAD_SONARQUBE_APP: YES
    # Based pn the branch, these are set in init.ps1. Might want to override in the UI. 
    UPLOAD_ARTIFACT: 
    DEPLOY: 
    SMOKE_TEST:
    # Override some default environment 
    JAVA_HOME: C:\Program Files\Java\jdk11
    PATH: C:\Program Files\Java\jdk11;$(PATH) # cannot use $(JAVA_HOME)
  
  install:
    - ps: appveyor/init.ps1
    - ps: appveyor/install_api.ps1
    - ps: appveyor/install_app.ps1    

  before_build:
    - ps: appveyor/before_build_api.ps1
    - ps: appveyor/before_build_app.ps1

  build_script:
    - ps: appveyor/build_pre.ps1
    - ps: appveyor/build_api.ps1
    - ps: appveyor/build_app.ps1

  # Order matters, Need to run app first to generate the lcov 
  # The sonarqube end in api will upload it 
  after_build:
    - ps: appveyor/after_build_test_unit_app.ps1
    - ps: appveyor/after_build_test_unit_api.ps1
    - ps: appveyor/after_build_test_unit_post.ps1

  test_script:
    - ps: appveyor/test_integration_api.ps1

  before_deploy:
    - ps: appveyor/before_deploy_api.ps1

  deploy_script:
    - ps: appveyor/deploy.ps1

  after_deploy:
    - ps: appveyor/after_deploy_smoke.ps1

  on_success:
    - ps: appveyor/success.ps1

  on_failure:
    - ps: appveyor/failure.ps1
    
  on_finish:
    - ps: appveyor/finish.ps1

  notifications:
  - provider: Email
    to:
    - '{{commitAuthorEmail}}'
    subject: '{{projectName}} build status is {{status}}'
    message: >-
      See:<br>
      {{buildUrl}}<br>
      https://github.com/bellrichm/weather/tree/{{branch}}<br>
      https://sonarcloud.io/dashboard?branch={{branch}}&id=weather<br>
      https://coveralls.io/github/bellrichm/weather?branch={{branch}}<br>
      <br>
      http://bellrichm-weather.azurewebsites.net<br>
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false 
