-
  branches:
    only:
      - master

  version: 1.0.{build}

  environment:
    COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
    SONARQUBE_REPO_TOKEN: ${SONARQUBE_REPO_TOKEN}
    AZURE_PW: ${AZURE_PW}
    ARTIFACT_NAME: ${ARTIFACT_NAME}
    BRANCH_NAME: ${BRANCH_NAME}
    DEPLOY: ${DEPLOY}

  # cannot be a script, because this is before the pull of the code
  # just trying to short circuit a build if not for expected branch
  init:
    - ps: >-
        Write-Host "******************************** Init ********************************"
        If ($env:APPVEYOR_REPO_BRANCH -eq $env:BRANCH_NAME)
        {
          $env:APPVEYOR_SKIP_FINALIZE_ON_EXIT = true;
          Exit-AppVeyorBuild
        }

  install:
    - ps: appveyor/init.ps1
    - ps: appveyor/install.ps1

  before_build:
    - ps: appveyor/before_build.ps1

  build_script:
    - ps: appveyor/build.ps1

  after_build:
    - ps: appveyor/after_build.ps1

  test_script:
    - ps: appveyor/test.ps1

  before_deploy:
    - ps: appveyor/before_deploy.ps1

  deploy_script:
    - ps: appveyor/deploy.ps1

  after_deploy:
    - ps: appveyor/after_deploy.ps1