-
  branches:
    only:
      - master

  version: 1.0.{build}

  environment:
    COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
    SONARQUBE_REPO_TOKEN: ${SONARQUBE_REPO_TOKEN}
    AZURE_PW: ${AZURE_PW}
    ARTIFACT_NAME: ${ARTIFACT_NAME}
    BRANCH_NAME: ${BRANCH_NAME}
    DEPLOY: ${DEPLOY}

  # cannot be a script, because this is before the pull of the code
  # just trying to short circuit a build if not for expected branch
  init:
    - echo "******************************** Init ********************************"
    - rem set
    - IF NOT "%APPVEYOR_REPO_BRANCH%"=="%BRANCH_NAME%" (
      set APPVEYOR_SKIP_FINALIZE_ON_EXIT=true & appveyor exit)

  install:
    - cmd: appveyor/init.cmd
    - cmd: appveyor/install.cmd

  build_script:
    - cmd: appveyor/build.cmd

  after_build:
    - cmd: appveyor/after_build.cmd
    - appveyor PushArtifact %ARTIFACT_NAME%.zip -DeploymentName %ARTIFACT_NAME% -type WebDeployPackage

  test_script: appveyor/test.cmd

  before_deploy:
    - cmd: appveyor/before_deploy.cmd

  deploy_script:
    - cmd: appveyor/deploy.cmd

  after_deploy:
    - cmd: appveyor/after_deploy.cmd