-
  branches:
    only:
      - master

  version: 1.0.{build}

  environment:
    COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
    SONARQUBE_REPO_TOKEN: ${SONARQUBE_REPO_TOKEN}
    AZURE_PW: ${AZURE_PW}
    ARTIFACT_NAME: ${ARTIFACT_NAME}
    BRANCH_NAME: ${BRANCH_NAME}
    DEPLOY: ${DEPLOY}

  install:
    - cmd: appveyor/install.cmd

  build_script:
    - cmd: appveyor/build.cmd

  test_script: appveyor/test.cmd

  artifacts:
    - path: dist
      name: ${ARTIFACT_NAME}
      type: WebDeployPackage

  before_deploy:
    - cmd: appveyor/before_deploy.cmd

  deploy:
    - provider: WebDeploy
      server: https://bellrichm-weather.scm.azurewebsites.net:443/msdeploy.axd?site=bellrichm-weather
      website: bellrichm-weather
      username: $bellrichm-weather
      password:
        secure: 9XB+JI35ertTWfWmF/0oVQ==
      artifact: ${ARTIFACT_NAME}
      aspnet_core: true
      remove_files: true
      app_offline: true
      skip_dirs: '\\logs;\\Data'
      on:
        DEPLOY: YES

  after_deploy:
    - cmd: appveyor/after_deploy.cmd