// <auto-generated />

using System;
using System.Runtime.Serialization;
using BellRichM.Attribute.CodeCoverage;

namespace BellRichM.Identity.Api.Exceptions
{
	[Serializable]
	public abstract class RoleException : Exception
	{
   		public string Code {get {return _code;} }

		#pragma warning disable CA2235 // TODO: Investigate, seems to be a false positive
		[NonSerialized]
		private string _code;
		#pragma warning restore CA2235

		[ExcludeFromCodeCoverage]
		public RoleException(string code) : base()
		{
            	_code = code;
		}

		[ExcludeFromCodeCoverage]
		public RoleException(string code, string message) : base(message)
		{
            	_code = code;
		}

		[ExcludeFromCodeCoverage]
		public RoleException(string code, string message, Exception innerException) : base(message, innerException)
		{
            	_code = code;
		}

		protected RoleException(SerializationInfo info, StreamingContext context) : base(info, context)
		{
            	_code = info.GetString("Code");
		}


		public override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
            	if (info == null)
                		throw new ArgumentNullException("info");

            	base.GetObjectData(info, context);
            	info.AddValue("Code", Code);
		}
	}
}